services:
    web:
        build:
            context: ./docker/php-7.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
                WWWUSER: 1000
        ports:
            - '8080:8080'
        environment:
            WWWUSER: 1000
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - network-app
networks:
    network-app:
        driver: bridge
